### PR TITLE
Create Locale_UK

### PR DESCRIPTION
**Pull request by GIGABAIT93**

### CODE REVIEW

**Comment by Zrips** [comment]
UK? Os should it be UA?

**Comment by GIGABAIT93** [comment]
it should be Ukraine


пт, 18 лист. 2022, 14:04 користувач Zrips ***@***.***> пише:

**Comment by NONPLAYT** [comment]
if this ukraine, rename file from UK to UA. check this https://en.wikipedia.org/wiki/List_of_ISO_3166_country_codes

**Comment by mrfloris** [comment]
I agree, the country code isn't UK it's UA as far as I am aware.

**Pull request merged**
